inject:
  - id: support
    file: test/test.txt
    target: test/test.md
    pattern: "<!-- auto-support -->"
  - id: hello
    command: echo 'hello world'
    target: test/test.txt
  - id: test
    url: https://test.com/content.html
    target: [test/test.html]

  # Invalid
  - id: does not have a source
    target: [test/test.html]
  - id: source is empty
    command:
    target: [test/test.html]
